-- AddField: logistics fields on Order
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "trackingCode" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "courierName" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "shippingLabelUrl" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "invoiceXmlUrl" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "invoicePdfUrl" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "isBundle" BOOLEAN NOT NULL DEFAULT false;

-- AddField: autoGenerated on PurchaseOrder
ALTER TABLE "PurchaseOrder" ADD COLUMN IF NOT EXISTS "autoGenerated" BOOLEAN NOT NULL DEFAULT false;

-- CreateTable: Bundle
CREATE TABLE IF NOT EXISTS "Bundle" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "price" DOUBLE PRECISION NOT NULL,
    "image" TEXT,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Bundle_pkey" PRIMARY KEY ("id")
);

-- CreateTable: BundleItem
CREATE TABLE IF NOT EXISTS "BundleItem" (
    "id" SERIAL NOT NULL,
    "bundleId" TEXT NOT NULL,
    "productId" TEXT NOT NULL,
    "quantity" INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT "BundleItem_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey: BundleItem -> Bundle
ALTER TABLE "BundleItem" ADD CONSTRAINT "BundleItem_bundleId_fkey"
  FOREIGN KEY ("bundleId") REFERENCES "Bundle"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey: BundleItem -> Product
ALTER TABLE "BundleItem" ADD CONSTRAINT "BundleItem_productId_fkey"
  FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
