import { Router, Request, Response } from "express";
import { db } from "../../../lib/db";
import { z } from "zod";
import { sendError } from "../lib/errors";

const router = Router();

const PurchaseSchema = z.object({
  supplierId: z.string(),
  branchId: z.string(),
  notes: z.string().optional().nullable(),
  status: z.enum(["DRAFT", "PENDING", "RECEIVED", "CANCELLED"]).optional().default("PENDING"),
  items: z.array(z.object({
    productId: z.string(),
    quantity: z.number().int().positive(),
    unitCost: z.number().positive()
  })).min(1)
});

// GET /api/admin/purchases — Lista de compras
router.get("/", async (req: Request, res: Response) => {
  const { status, supplierId, autoGenerated } = req.query;
  const where: any = {};
  if (status) where.status = status;
  if (supplierId) where.supplierId = supplierId;
  if (autoGenerated !== undefined) where.autoGenerated = autoGenerated === 'true';

  const purchases = await db.purchaseOrder.findMany({
    where,
    include: {
      supplier: { select: { name: true } },
      branch: { select: { name: true } },
      _count: { select: { items: true } }
    },
    orderBy: { createdAt: "desc" }
  });
  res.json(purchases);
});

// GET /api/admin/purchases/:id — Detalle de compra
router.get("/:id", async (req: Request, res: Response) => {
  const { id } = req.params;
  const purchase = await db.purchaseOrder.findUnique({
    where: { id },
    include: {
      supplier: true,
      branch: true,
      items: {
        include: { product: { select: { name: true, image: true } } }
      }
    }
  });
  if (!purchase) return sendError(res, 404, { code: "NOT_FOUND", message: "Compra no encontrada" });
  res.json(purchase);
});

// POST /api/admin/purchases — Crear nueva compra (Entrada de mercancía)
router.post("/", async (req: Request, res: Response) => {
  const parsed = PurchaseSchema.safeParse(req.body);
  if (!parsed.success) return sendError(res, 400, { code: "VALIDATION_ERROR", message: "Datos inválidos", details: parsed.error });

  const { supplierId, branchId, notes, items, status } = parsed.data;
  const totalAmount = items.reduce((sum, i) => sum + (i.quantity * i.unitCost), 0);

  // Generar un ID interno simple OC-XXXX
  const lastOrder = await db.purchaseOrder.findFirst({ orderBy: { createdAt: 'desc' } });
  const nextNum = lastOrder ? parseInt(lastOrder.internalId.split('-')[1]) + 1 : 1001;
  const internalId = `OC-${nextNum}`;

  const purchase = await db.purchaseOrder.create({
    data: {
      internalId,
      supplierId,
      branchId,
      notes,
      totalAmount,
      status: status || "PENDING",
      items: {
        create: items
      }
    },
    include: { items: true }
  });

  res.status(201).json(purchase);
});

// PUT /api/admin/purchases/:id/status — Actualizar estado y afectar stock
router.put("/:id/status", async (req: Request, res: Response) => {
  const { id } = req.params;
  const { status } = req.body; // PENDING, RECEIVED, CANCELLED

  const existing = await db.purchaseOrder.findUnique({
    where: { id },
    include: { items: true }
  });

  if (!existing) return sendError(res, 404, { code: "NOT_FOUND", message: "Compra no encontrada" });
  if (existing.status === "RECEIVED") return sendError(res, 400, { code: "BAD_REQUEST", message: "Esta compra ya fue recibida y no se puede modificar" });
  if (existing.status === "CANCELLED") return sendError(res, 400, { code: "BAD_REQUEST", message: "Esta compra ya fue cancelada" });

  if (status === "RECEIVED") {
    // ─── LÓGICA DE ACTUALIZACIÓN DE STOCK ─────────────────────────────────────
    await db.$transaction(async (tx) => {
      // 1. Marcar como recibida
      await tx.purchaseOrder.update({
        where: { id },
        data: { 
          status: "RECEIVED",
          receivedAt: new Date()
        }
      });

      // 2. Incrementar stock e intentar actualizar costos
      for (const item of existing.items) {
        // Actualizar o crear inventario en la sucursal destino
        await tx.inventory.upsert({
          where: {
            productId_branchId: {
              productId: item.productId,
              branchId: existing.branchId
            }
          },
          update: {
            stock: { increment: item.quantity }
          },
          create: {
            productId: item.productId,
            branchId: existing.branchId,
            stock: item.quantity
          }
        });

        // RECOMENDACIÓN: Actualizar el costo base del producto con el último costo de compra
        await tx.product.update({
          where: { id: item.productId },
          data: { cost: item.unitCost }
        });
      }
    });

    return res.json({ success: true, message: "Inventario actualizado correctamente" });
  }

  // Otros cambios de estado simples (ej: Cancelar)
  const updated = await db.purchaseOrder.update({
    where: { id },
    data: { status }
  });

  res.json(updated);
});

import { posEventEmitter } from "../lib/events";

// GET /api/admin/purchases/cron/restock
// Endpoint automatizado para detectar stock bajo y generar DRAFTS de compras
router.get("/cron/restock", async (req: Request, res: Response) => {
  // Nota: En producción, proteger con un CRON_SECRET token en el Header
  
  try {
    const products = await db.product.findMany({
      where: { minStock: { gt: 0 } },
      include: {
        inventories: true,
      }
    });

    const branches = await db.branch.findMany({ select: { id: true, name: true } });
    
    // Necesitamos un "Proveedor Sugerido" por defecto para no romper el schema
    let defaultSupplier = await db.supplier.findFirst({ where: { name: "Proveedor Automático" } });
    if (!defaultSupplier) {
      defaultSupplier = await db.supplier.create({
        data: { name: "Proveedor Automático", notes: "Creado automáticamente por sistema de restock" }
      });
    }

    let ordersCreated = 0;

    for (const branch of branches) {
      // Find what needs to be restocked for this branch
      const itemsToOrder = [];

      for (const prod of products) {
        // Obviamos la branch online para abastecimiento físico, 
        // a menos que la online tenga su propio inventario real.
        const inv = prod.inventories.find(i => i.branchId === branch.id);
        const stock = inv ? inv.stock : 0;

        if (stock < prod.minStock) {
          const qtyNeeded = prod.minStock - stock;
          // Sugerir siempre reabastecer al menos 5 o lo que falte
          const suggestQty = Math.max(5, qtyNeeded); 
          itemsToOrder.push({
            productId: prod.id,
            quantity: suggestQty,
            unitCost: prod.cost || (prod.price * 0.4) // default cost heuristic vs real cost
          });
        }
      }

      if (itemsToOrder.length > 0) {
        const totalAmount = itemsToOrder.reduce((sum, item) => sum + (item.quantity * item.unitCost), 0);
        
        const lastOrder = await db.purchaseOrder.findFirst({ orderBy: { createdAt: 'desc' } });
        const nextNum = lastOrder ? parseInt(lastOrder.internalId.split('-')[1]) + 1 : 1001;
        const internalId = `OC-${nextNum}`;

        await db.purchaseOrder.create({
          data: {
            internalId,
            supplierId: defaultSupplier.id,
            branchId: branch.id,
            totalAmount,
            status: "DRAFT",
            autoGenerated: true,
            notes: `Orden autogenerada por nivel bajo inventario: Sucursal ${branch.name}`,
            items: {
              create: itemsToOrder
            }
          }
        });
        ordersCreated++;
      }
    }

    if (ordersCreated > 0) {
      posEventEmitter.emit("low_stock_draft");
    }

    res.json({ message: "Cron completado", ordersCreated });
  } catch (error: any) {
    console.error("Cron Error:", error);
    res.status(500).json({ error: "No se pudo ejecutar el cron de restock" });
  }
});

export default router;
